#!/bin/sh
git log -1 --pretty=%h
IMAGE_REPO_USERNAME=zmaker123
IMAGE_NAME=lci-ubi-aws
TAG_GIT_COMMIT_HASH=$(git log -1 --pretty=%h)
TAG_OS_VERSION=ubi_8.1
TAG=${TAG_OS_VERSION}-${TAG_GIT_COMMIT_HASH}
IMAGE=${IMAGE_REPO_USERNAME}/${IMAGE_NAME}:${TAG}

echo "IMAGE = $IMAGE"
docker build -f ./Dockerfile --tag ${IMAGE_REPO_USERNAME}/${IMAGE_NAME}:${TAG} .
docker tag ${IMAGE_REPO_USERNAME}/${IMAGE_NAME}:${TAG} ${IMAGE_REPO_USERNAME}/${IMAGE_NAME}:${TAG_OS_VERSION}-latest